name: Java

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  my_matrix:
    strategy:
        max-parallel: 1
        matrix:
            os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup rust
      run: rustup default 1.75.0
    - name: Download GraalJVM
      run: wget https://download.oracle.com/graalvm/21/archive/graalvm-jdk-21.0.2_linux-x64_bin.tar.gz
    - name: Extract GraalJVM
      run: tar -xvf graalvm-jdk-21.0.2_linux-x64_bin.tar.gz
    - name: Extract cnr-2000 so we can test from scratch
      run: mkdir tmp && cp webgraph-rs/tests/data/cnr-2000.{graph,properties} tmp/ 
    - name: Run speed test
      run: "./exp.sh tmp/cnr-2000"
