name: Java

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  JVMOPTS: "-server -Xss256K -XX:PretenureSizeThreshold=512M -XX:MaxNewSize=4G -XX:+UseLargePages -XX:+UseTransparentHugePages -XX:+UseNUMA -XX:+UseTLAB -XX:+ResizeTLAB"
  GRAPH: "webgraph-rs/tests/data/cnr-2000"
  NODES_NUM: "325557"

jobs:
  my_matrix:
    strategy:
        max-parallel: 1
        matrix:
            os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Download GraalJVM
      run: wget https://download.oracle.com/graalvm/21/archive/graalvm-jdk-21.0.2_linux-x64_bin.tar.gz
    - name: Extract GraalJVM
      run: tar -xvf graalvm-jdk-21.0.2_linux-x64_bin.tar.gz
    - name: Run speed test
      run: "CLASSPATH=$(find -iname \\*.jar | paste -d: -s -) $GITHUB_WORKSPACE/graalvm-jdk-21.0.2+13.1/bin/java $JVMOPTS -Xmx1G it.unimi.dsi.big.webgraph.test.SpeedTest $GRAPH -r $NODES_NUM -m"
    - name: Run bfs test
      run: "CLASSPATH=$(find -iname \\*.jar | paste -d: -s -) $GITHUB_WORKSPACE/graalvm-jdk-21.0.2+13.1/bin/java $JVMOPTS -Xmx1G it.unimi.dsi.law.big.graph.BFS -m --repeats 3 $GRAPH - "